// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project2;

{ITE} {DFMFileType} {U_Accesorios.dfm}
{ITE} {DFMFileType} {U_Caract.dfm}
{ITE} {DFMFileType} {U_module.dfm}
{ITE} {DFMFileType} {U_principal.dfm}
{ITE} {RCFileType} {Win32\Debug\Project2_DRC.rc}

{$R 'U_Accesorios.dfm' 'Form1:TForm'}
{$R 'U_Caract.dfm' 'Form3:TForm'}
{$R 'U_module.dfm' 'DataModule3:TDataModule'}
{$R 'U_principal.dfm' 'Form2:TForm'}
{$R 'Win32\Debug\Project2_DRC.res' 'Win32\Debug\Project2_DRC.rc'}

{$E ESP}

begin
end.
